[project]
name = "coupling-analyzer"
version = "0.1.0"
description = ""
authors = [
    {name = "Almaz Ilaletdinov",email = "a.ilaletdinov@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "libcst (>=1.8.5,<2.0.0)"
]

[project.scripts]
unpbs = "unpbs.entry:main"

[tool.poetry]
packages = [{include = "unpbs"}]

[tool.poetry.group.dev.dependencies]
pytest = "8.4.2"
ruff = "0.13.2"
pytest-cov = "7.0.0"
mypy = "1.18.2"
deltaver = "^0.2.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["ALL"]
fixable = [
  "ALL",
]
ignore = [
  "ARG001",  # Unused function argument
  "ARG002",  # Unused method argument
  "D203",    # no-blank-line-before-class
  "D213",    # multi-line-summary-first-line
  "D401",    # First line of docstring should be in imperative mood
  "D418",    # Function decorated with `@overload` shouldn't contain a docstring
  "FBT001",  # Boolean-typed positional argument in function definition
  "FBT002",  # Boolean-typed positional argument in function definition
  "FIX002",  # Line contains T0DO, consider resolving the issue
  "FLY002",  # We not use f-strings
  "RUF100",  # WPS primary linter
  "RUF001",  # Project contain cyrillic symbols
  "RUF002",  # Project contain cyrillic symbols
  "RET505",  # Unnecessary `elif` after `return` statement
  "RET506",  # Unnecessary `elif` after `raise` statement
  "UP030",   # We use explicit references
  "UP032",   # We not use f-strings
  "UP004",   # Class `PrayerReaction` inherits from `object`
  "TD",      # "t0do" formats
  "PLR630",  # We disrespect staticmethods
  "TC003",   # Move standard library import `...` into a type-checking block
  "TC001",   # Move application import into a type-checking block
]

[tool.ruff]
line-length = 120
target-version = "py39"
output-format = "concise"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "S101",    # use of `assert` detected
  "S603",
  "S607",
  "PLR2004", # Magic value
  "PLR0913", # Too many arguments to function call
  "INP001",  # Add an `__init__.py`. Tests is closed to import
]